# SmBld, ExtLt, Light, Medm, Text, Thin 
# Font
font_size      10
font_family      JetBrains Mono Thin
# font_family      JetBrains Mono Bold
clipboard_control write-clipboard write-primary read-clipboard read-primary

adjust_line_height -1
adjust_column_width 0
adjust_baseline 0
cursor_shape            block
text_composition_strategy platform

enable_audio_bell no
cursor_trail 0
background_opacity 0.93
#hide_window_decorations yes
confirm_os_window_close 0
shell_integration  no-cursor
window_padding_width 2 4 2 4

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
# include current-theme.conf
# include solarised_dark.conf
include tokyo_night.conf
# include rosepine.conf 
# include rosepine_dawn.conf
# END_KITTY_THEME

map ctrl+shift+w no_op
