# Status bar colors and style
set-option -g status-style "bg=#000000,fg=#ffffff"

# Pane borders
set-option -g pane-border-style "fg=#000000"
set-option -g pane-active-border-style "fg=#ffffff"

# Message style
set-option -g message-style "bg=#000000,fg=#ffffff,bold"
set-option -g message-command-style "bg=#000000,fg=#ffffff,bold"

# # Status left (session name)
# set-option -g status-left "#[fg=$accent_color,bold]  #S #[fg=$inactive_color]│ "

# # Copy mode styling
set-option -g mode-style "bg=#ffffff,fg=#000000"

# # Clock mode
# set-option -g clock-mode-colour "$active_color"
# set-option -g clock-mode-style 24
