# Status bar colors and style
set-option -g status-style "bg=default,fg=#ffffff"
# set-option -g status-style "bg=default,fg=#000000"

# Pane borders
set-option -g pane-border-style "fg=#000000"
set-option -g pane-active-border-style "fg=#ffffff"
# set-option -g pane-active-border-style "fg=#000000"

# Message style
set-option -g message-style "bg=default,fg=#ffffff"
set-option -g message-command-style "bg=default,fg=#ffffff"

set-option -g status-left-length 30
set-option -g status-left "#[fg=#ffffff][#{=20:session_name}#[fg=#ffffff]] "
# set-option -g status-left "#[fg=#000000][#{=20:session_name}#[fg=#000000]] "

# # Copy mode styling
set-option -g mode-style "bg=#ffffff,fg=#000000"

# # Clock mode
# set-option -g clock-mode-colour "$active_color"
# set-option -g clock-mode-style 24
