# ~/.config/foot/foot.ini

# Main terminal settings
#shell=fish -c "fastfetch && fish"
#Alternative: font=IBM Plex Mono Medium:size=10
pad=6x10
resize-delay-ms=100

#font=JetBrains Mono:size=9.5:style=SemiBold
# include=/usr/share/foot/themes/rose-pine-dawn
# include=/usr/share/foot/themes/rose-pine
# include=/usr/share/foot/themes/dracula
include=/usr/share/foot/themes/tokyonight-storm
#include=/usr/share/foot/themes/solarized-dark
font=JetBrains Mono:size=10
#font=IBM Plex Mono:size=10


[bell]
urgent=no
notify=no

[scrollback]
lines=1000
multiplier=3.0

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[colors]
background=000000
# background=011628  
alpha=0.92

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

[text-bindings]
\x17 = Control+BackSpace
# nvim\x0a = Control+n
tmux-sessionizer.sh\x0a = Control+s

[search-bindings]
# Keep default search bindings

[mouse-bindings]
# Keep default mouse bindings
