animations {
  enabled = yes

  bezier = open,   0.2, 1.0, 0.4, 1.0
  bezier = close,  0.4, 0.0, 0.8, 0.6
  bezier = momentum,  0.0, 0.9, 0.15, 1.0
  bezier = linout,    0.0, 1.0, 0.0, 1.0

  animation = windowsIn,  1, 2, open,  popin 93%
  animation = windowsOut, 1, 1, close, popin 96%
    animation = windowsMove, 1, 2, open, slide

  animation = workspaces, 1, 3, momentum, slidevert

  animation = fade,       1, 2, open
  animation = border,     1, 8, linout
  animation = borderangle,1, 60, linout, loop
}
