# $wallDIR=$HOME/Pictures/wallpapers

# wallpaper stuff / More wallpaper options below

# exec-once = /home/shivank/scripts/walThemeGenerator.sh

#################
### AUTOSTART ###
#################

exec-once = awww-daemon 
exec-once = hyprpm reload 
exec-once = waybar &  
exec-once = connectwifi.sh &
exec-once = nm-applet &
exec-once = blueman-applet &
# exec-once = /usr/bin/emacs --daemon &
# exec-once = kclockd &
exec-once = hypridle &
exec-once = runWorkspaceIndicator.sh hypr & 
exec-once = kdeconnectd &
exec-once = nwg-wrapper-todo.sh & 
#exec-once = gamemode.sh 
