
windowrule = idle_inhibit fullscreen, opacity 1, match:fullscreen 1

# Picture-in-a-Picture (PIP) rules: Oddly, some need re-duplication.  This is because the window for
# PIP changes after on first launch, and will not inherant the rules...
windowrule = opacity 1, match:title ^(Picture-in-Picture)$ # for opacity: [focus num] [bg num]
# Interestingly, the opacity rule above doesn't need the reduplication?
windowrule = pin on, float on, size (monitor_w*0.25) (monitor_h*0.25), move ((monitor_w*0.72)) ((monitor_h*0.07)), match:title ^(Picture-in-Picture)$

# windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
# windowrulev2 = noanim,class:^(xwaylandvideobridge)$
# windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
# windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
# windowrulev2 = noblur,class:^(xwaylandvideobridge)$

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
#Opacity for all windows
windowrule = opacity 1, suppress_event maximize, match:class .*
windowrule = opacity 1, match:class vlc
windowrule = opacity 1, match:title Fake-Lock-Screen
windowrule = opacity 1, match:class mpv
windowrule = opacity 1, match:class org.kde.okular
windowrule = opacity 1, match:title ^(.*YouTube.*)$
# windowrulev2 = opacity 1,title:^(.*Obsidian.*)$
windowrule = opacity 1, match:title ^(.*HiMovies.*)$
windowrule = opacity 1, match:class com.obsproject.Studio
#Some settings for emacs
windowrule = opacity 0.95, match:class neovide

windowrule = float on, match:title Qalculate!
windowrule = float on, match:class Electron

#Conky 
windowrule = float on, border_size 0, match:class (?i)conky

# make terminal fully opaque 
windowrule = opacity 1, match:class com.mitchellh.ghostty
windowrule = opacity 1, match:class kitty
windowrule = opacity 1, match:class foot

windowrule = float on, match:class ^(tasty.javafx.launcher.LauncherFxApp)$, match:title ^(tastytrade)$
windowrule = float on, match:class ^(tasty.javafx.launcher.LauncherFxApp)$, match:title ^(tastycharts)$
windowrule = float on, match:class ^(tasty.javafx.launcher.LauncherFxApp)$, match:title ^(tastytrade - Portfolio Report)$
windowrule = float on, match:class ^(tasty.javafx.launcher.LauncherFxApp)$, match:title ^(Dashboard)$
# windowrulev2 = bordercolor $bordercolor2,floating:1
# windowrule = border_color $bordercolor2 $bordercolor2, match:pin 1


# Ignore maximize requests from apps. You'll probably like this.

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


# My custom workspace indicator rules
# windowrule = no_focus on, pin on, border_size 0, move ((monitor_w*0.983)) ((monitor_h*0.978)), match:class com.sd.workspaceindicator
# windowrulev2 = rounding 13,class:com.sd.workspaceindicator

# Example of how you can set window rules.
# This rule is for noborders and no rounded corners on workspace 4.
# // Causing error in recent update
# workspace = 4, gapsout:0, gapsin:0, border: 0, rounding:0

#making waybar blur
layerrule = blur on, ignore_alpha 0, match:namespace waybar

#For sway control centre
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window


#
# Defining workspace for some of the apps
# windowrulev2 = workspace 3,class:Code
# windowrulev2 = workspace 3,class:Emacs

# windowrulev2 = workspace 5,class:Spotify
# windowrulev2 = workspace 2,class:Brave-browser
# windowrulev2 = workspace 2,class:Qutebrowser
